import streamlit as st
import pandas as pd
import numpy as np
import os
import yaml
import sys
import plotly.express as px
import plotly.graph_objects as go

# Add src to path
sys.path.append(os.path.abspath('.'))

from src.inference import InferencePipeline

# Page configuration
st.set_page_config(
    page_title="Human vs AI Classifier",
    page_icon="🤖",
    layout="wide"
)

# Load configuration
@st.cache_resource
def load_config():
    with open('configs/config.yaml', 'r') as f:
        return yaml.safe_load(f)

config = load_config()

# Sidebar
st.sidebar.title("Settings")
model_files = [f for f in os.listdir(config['output']['models_dir']) if f.endswith('.pkl') and '_fitted' not in f]
selected_model = st.sidebar.selectbox("Select Model", model_files if model_files else ["No models found"])

# Title and Description
st.title("🛡️ AI-Generated Text Detector")
st.markdown("""
This application uses machine learning to distinguish between essays written by humans and those generated by AI models.
Enter an essay below to see the results.
""")

# Main Content
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("Input Essay")
    user_input = st.text_area("Paste the text here (at least 50 words recommended):", height=400)
    
    predict_button = st.button("Analyze Text", type="primary")

if predict_button and user_input:
    if len(user_input.split()) < 10:
        st.warning("Please enter more text for a more accurate prediction.")
    else:
        with st.spinner("Analyzing text characteristics..."):
            try:
                # Initialize pipeline
                model_path = os.path.join(config['output']['models_dir'], selected_model)
                pipeline = InferencePipeline(model_path)
                
                # Predict
                result = pipeline.predict(user_input)
                
                # Display Results
                with col2:
                    st.subheader("Analysis Results")
                    
                    if result['prediction'] == 1:
                        st.error(f"Prediction: {result['label']}")
                    else:
                        st.success(f"Prediction: {result['label']}")
                        
                    st.metric("Confidence Score", f"{result['confidence']*100:.1f}%")
                    
                    # Probability Gauge
                    fig = go.Figure(go.Indicator(
                        mode = "gauge+number",
                        value = result['probabilities']['ai'] * 100,
                        domain = {'x': [0, 1], 'y': [0, 1]},
                        title = {'text': "AI Probability %"},
                        gauge = {
                            'axis': {'range': [None, 100]},
                            'bar': {'color': "#EF553B" if result['prediction'] == 1 else "#00CC96"},
                            'steps': [
                                {'range': [0, 50], 'color': "lightgray"},
                                {'range': [50, 100], 'color': "gray"}
                            ],
                        }
                    ))
                    st.plotly_chart(fig, use_container_width=True)

                # Feature Breakdown
                st.divider()
                st.subheader("Linguistic Characteristics")
                feat_col1, feat_col2, feat_col3, feat_col4 = st.columns(4)
                
                features = result['linguistic_features']
                feat_col1.metric("Avg Sentence Length", f"{features['avg_sentence_len']:.1f}")
                feat_col2.metric("Vocabulary Richness (TTR)", f"{features['ttr']:.2f}")
                feat_col3.metric("Readability (Flesch)", f"{features['flesch_reading_ease']:.1f}")
                feat_col4.metric("Burstiness Score", f"{features['burstiness']:.2f}")
                
            except Exception as e:
                st.error(f"Analysis failed: {e}")
                st.info("Make sure you have trained and saved at least one model first.")
else:
    with col2:
        st.info("Paste text and click 'Analyze Text' to see the breakdown.")
        st.image("https://img.icons8.com/clouds/200/000000/brain.png")

# Footer
st.divider()
st.caption("Human vs AI Classifier - Built for GenAI Project Walkthrough")
